const jCategory = [

    {
        index: 0,
        image: "../assets/images/google.png",
        title: "Web Developer",
        rate: "$900-$1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "02",
        hours: "50h / week",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et repellat sit doloremque officia, obcaecati, doloribus nisi veritatis! Voluptates nulla ipsam laudantium amet aliquid impedit repellat cupiditate odio eaque deserunt similique veritatis, assumenda, non accusamus perspiciatis dolores natus ea. Aut molestias nisi, repellendus a amet praesentium tenetur voluptatibus provident odio ducimus doloremque ex accusamus quos necessitatibus excepturi quo nulla suscipit sit et assumenda alias facere doloribus. Enim ab distinctio repellat incidunt ducimus minima beatae doloremque pariatur ratione maiores aut id, officiis voluptate vero ad sit, dignissimos voluptatum explicabo doloribus nulla quibusdam libero architecto! Sapiente quas rerum beatae aliquid! Enim unde quia ipsum ullam qui molestias laborum. Assumenda quae consequatur doloribus eveniet quo! A commodi laudantium laboriosam minima quis molestias!",
        workplace: "-Work from home",
        education: "-Bachelor's degree",
        experience: "-2 to 5 year(s)",
    },
    {
        index: 1,
        image: "../assets/images/linkedin.png",
        title: "Business Associate",
        rate: "$700-$1000/m",
        av: "Part Time",
        companyName: "LinkedIn",
        location: "USA",
        vacancy: "01",
        hours: "30h / week",
        description: "Assist with business operations, client management, and communication. Analyze data to identify business opportunities. Collaborate with teams to ensure seamless workflow and project execution.",
        workplace: "-Hybrid (Office + Work from home)",
        education: "-Bachelor's degree in Business Administration or similar",
        experience: "-1 to 3 year(s)",
    },
    {
        index: 2,
        image: "../assets/images/uber.png",
        title: "Software Developer",
        rate: "$1000-$1500/m",
        av: "Full Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "03",
        hours: "40h / week",
        description: "Develop and maintain scalable software solutions for the Uber platform. Work with cross-functional teams to ensure robust and efficient delivery of projects.",
        workplace: "-Work from office",
        education: "-Bachelor's degree in Computer Science or similar",
        experience: "-3 to 5 year(s)",
    },
    {
        index: 3,
        image: "../assets/images/instagram.png",
        title: "Social Marketing",
        rate: "$800-$1100/m",
        av: "Freelancer",
        companyName: "Instagram",
        location: "Remote",
        vacancy: "02",
        hours: "Flexible hours",
        description: "Plan and execute social media strategies. Manage Instagram campaigns and engage with audiences to boost brand visibility and user interaction.",
        workplace: "-Remote work",
        education: "-Open to all with relevant experience",
        experience: "-1 to 4 year(s)",
    },
    {
        index: 4,
        image: "../assets/images/yahoo.png",
        title: "Web Developer",
        rate: "$850-$1200/m",
        av: "Part Time",
        companyName: "Yahoo",
        location: "USA",
        vacancy: "02",
        hours: "25h / week",
        description: "Design and implement web interfaces and back-end solutions for Yahoo's platform. Optimize performance and ensure responsive design.",
        workplace: "-Work from office",
        education: "-Bachelor's degree in IT or similar",
        experience: "-2 to 4 year(s)",
    },
    {
        index: 5,
        image: "../assets/images/google.png",
        title: "Android Developer",
        rate: "$950-$1300/m",
        av: "Freelancer",
        companyName: "Google",
        location: "USA",
        vacancy: "01",
        hours: "Flexible hours",
        description: "Develop Android applications and features for Google's products. Collaborate with designers and backend developers to create seamless experiences.",
        workplace: "-Remote work",
        education: "-Bachelor's degree in Computer Science or similar",
        experience: "-2 to 5 year(s)",
    },




    // {
    //     index: 0,
    //     image: "../assets/images/google.png",
    //     title: "Web Developer",
    //     rate: "$900-$1200/m",
    //     av: "Full Time",
    //     companyName: "Google",
    //     location: "USA",
    //     vacancy: "02",
    //     hours: "50h / week",
    //     description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et repellat sit doloremque officia, obcaecati, doloribus nisi veritatis! Voluptates nulla ipsam laudantium amet aliquid impedit repellat cupiditate odio eaque deserunt similique veritatis, assumenda, non accusamus perspiciatis dolores natus ea. Aut molestias nisi, repellendus a amet praesentium tenetur voluptatibus provident odio ducimus doloremque ex accusamus quos necessitatibus excepturi quo nulla suscipit sit et assumenda alias facere doloribus. Enim ab distinctio repellat incidunt ducimus minima beatae doloremque pariatur ratione maiores aut id, officiis voluptate vero ad sit, dignissimos voluptatum explicabo doloribus nulla quibusdam libero architecto! Sapiente quas rerum beatae aliquid! Enim unde quia ipsum ullam qui molestias laborum. Assumenda quae consequatur doloribus eveniet quo! A commodi laudantium laboriosam minima quis molestias!",
    //     workplace:  "-work form home",
    //     education:"-Bachelor's degree",
    //     experience:"-2 to 5 year(s)",
    // },
    // {
    //     index: 1,
    //     image: "../assets/images/linkedin.png",
    //     title: "Business Associate",
    //     rate: "$900-$1200/m",
    //     av: "Part Time",

    // },
    // {
    //     index: 2,
    //     image: "../assets/images/uber.png",
    //     title: "Software Developer",
    //     rate: "$900-$1200/m",
    //     av: "Full Time",

    // },
    // {
    //     index: 3,
    //     image: "../assets/images/instagram.png",
    //     title: "Social Marketing",
    //     rate: "$900-$1200/m",
    //     av: "Freelancer",

    // },
    // {
    //     index: 4,
    //     image: "../assets/images/yahoo.png",
    //     title: "Web Developer",
    //     rate: "$900-$1200/m",
    //     av: "Part Time",

    // },
    // {
    //     index: 5,
    //     image: "../assets/images/google.png",
    //     title: "Android Developer",
    //     rate: "$900-$1200/m",
    //     av: "Freelancer",

    // },

];  